#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

	
wclean libso combustionModels
wclean libso lagrangian/parcel
wclean libso finiteVolume


#------------------------------------------------------------------------------
